import {
  Wifi,
  Shield,
  Zap,
  Car,
  BookOpen,
  Utensils,
  WashingMachine,
  Sparkles,
  Phone,
  Mail,
  MapPin,
  Clock,
  Instagram,
  Facebook,
  Linkedin,
  Youtube,
  MessageCircle,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Play,
  Check,
  Star,
  Map,
  Compass,
  Calendar,
  AlertCircle,
  Bed,
  Bath,
  Shirt,
  Home,
  Coffee,
  Twitter,
  Heart,
  Leaf,
  Tv,
  Waves,
  Smile,
  Gift
} from 'lucide-react';

export const Icons = {
  // Amenities
  coffee: Coffee,
  wifi: Wifi,
  security: Shield,
  powerBackup: Zap,
  parking: Car,
  studyArea: BookOpen,
  dining: Utensils,
  laundry: WashingMachine,
  housekeeping: Sparkles,
  bed: Bed,
  bath: Bath,
  shirt: Shirt,
  sparkles: Sparkles,
  utensils: Utensils,
  zap: Zap,
  shield: Shield,
  heart: Heart,
  leaf: Leaf,
  tv: Tv,
  waves: Waves,
  smile: Smile,
  gift: Gift,
  
  // Contact & Social
  phone: Phone,
  email: Mail,
  address: MapPin,
  hours: Clock,
  instagram: Instagram,
  facebook: Facebook,
  linkedin: Linkedin,
  youtube: Youtube,
  whatsapp: MessageCircle,
  twitter: Twitter,
  
  // Navigation & General UI
  menu: Menu,
  close: X,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronRight: ChevronRight,
  play: Play,
  check: Check,
  star: Star,
  map: Map,
  compass: Compass,
  calendar: Calendar,
  alert: AlertCircle,
  home: Home,
} as const;

export type IconType = keyof typeof Icons;
