import {
  Wifi,
  Shield,
  Zap,
  Car,
  BookOpen,
  Utensils,
  WashingMachine,
  Sparkles,
  Phone,
  Mail,
  MapPin,
  Clock,
  Instagram,
  Facebook,
  Linkedin,
  Youtube,
  MessageCircle,
  Menu,
  X,
  ArrowRight,
  ArrowLeft,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  Play,
  Check,
  Star,
  Map,
  Compass,
  Calendar,
  AlertCircle,
  Bed,
  Bath,
  Shirt,
  Home,
  Coffee,
  Twitter,
  Heart,
  Leaf,
  Tv,
  Waves,
  Smile,
  Gift,
  Brush,
  Wind,
  Droplets,
  ArrowUpSquare,
  AirVent,
  ChefHat,
  Users
} from 'lucide-react';

export const Icons = {
  // Amenities
  coffee: Coffee,
  Coffee: Coffee,
  wifi: Wifi,
  Wifi: Wifi,
  security: Shield,
  Shield: Shield,
  powerBackup: Zap,
  Zap: Zap,
  parking: Car,
  Car: Car,
  studyArea: BookOpen,
  BookOpen: BookOpen,
  dining: Utensils,
  Utensils: Utensils,
  laundry: WashingMachine,
  WashingMachine: WashingMachine,
  housekeeping: Sparkles,
  Sparkles: Sparkles,
  bed: Bed,
  Bed: Bed,
  bath: Bath,
  Bath: Bath,
  shirt: Shirt,
  Shirt: Shirt,
  sparkles: Sparkles,
  utensils: Utensils,
  zap: Zap,
  shield: Shield,
  heart: Heart,
  Heart: Heart,
  leaf: Leaf,
  Leaf: Leaf,
  tv: Tv,
  Tv: Tv,
  waves: Waves,
  Waves: Waves,
  smile: Smile,
  Smile: Smile,
  gift: Gift,
  Gift: Gift,
  brush: Brush,
  Brush: Brush,
  wind: Wind,
  Wind: Wind,
  droplets: Droplets,
  Droplets: Droplets,
  lift: ArrowUpSquare,
  ArrowUpSquare: ArrowUpSquare,
  ac: AirVent,
  AirVent: AirVent,
  chefHat: ChefHat,
  ChefHat: ChefHat,
  cafe: Coffee,
  
  // Contact & Social
  phone: Phone,
  Phone: Phone,
  email: Mail,
  Mail: Mail,
  address: MapPin,
  MapPin: MapPin,
  hours: Clock,
  Clock: Clock,
  instagram: Instagram,
  Instagram: Instagram,
  facebook: Facebook,
  Facebook: Facebook,
  linkedin: Linkedin,
  Linkedin: Linkedin,
  youtube: Youtube,
  Youtube: Youtube,
  whatsapp: MessageCircle,
  MessageCircle: MessageCircle,
  twitter: Twitter,
  Twitter: Twitter,
  
  // Navigation & General UI
  menu: Menu,
  Menu: Menu,
  close: X,
  X: X,
  arrowRight: ArrowRight,
  ArrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  ArrowLeft: ArrowLeft,
  chevronDown: ChevronDown,
  ChevronDown: ChevronDown,
  chevronUp: ChevronUp,
  ChevronUp: ChevronUp,
  chevronRight: ChevronRight,
  ChevronRight: ChevronRight,
  users: Users,
  Users: Users,
  play: Play,
  Play: Play,
  check: Check,
  Check: Check,
  star: Star,
  Star: Star,
  map: Map,
  Map: Map,
  compass: Compass,
  Compass: Compass,
  calendar: Calendar,
  Calendar: Calendar,
  alert: AlertCircle,
  AlertCircle: AlertCircle,
  home: Home,
  Home: Home,
} as const;

export type IconType = keyof typeof Icons;
