export interface EnvConfig {
  FIREBASE_API_KEY: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
  FIREBASE_MESSAGING_SENDER_ID: string;
  FIREBASE_APP_ID: string;
  FIREBASE_MEASUREMENT_ID: string;
  GOOGLE_MAPS_API_KEY: string;
  RAZORPAY_KEY_ID: string;
}

const metaEnv = (import.meta as any).env || {};

export const env: EnvConfig = {
  FIREBASE_API_KEY: (metaEnv.NEXT_PUBLIC_FIREBASE_API_KEY || metaEnv.VITE_FIREBASE_API_KEY || '') as string,
  FIREBASE_AUTH_DOMAIN: (metaEnv.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || metaEnv.VITE_FIREBASE_AUTH_DOMAIN || '') as string,
  FIREBASE_PROJECT_ID: (metaEnv.NEXT_PUBLIC_FIREBASE_PROJECT_ID || metaEnv.VITE_FIREBASE_PROJECT_ID || '') as string,
  FIREBASE_STORAGE_BUCKET: (metaEnv.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || metaEnv.VITE_FIREBASE_STORAGE_BUCKET || '') as string,
  FIREBASE_MESSAGING_SENDER_ID: (metaEnv.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID || '') as string,
  FIREBASE_APP_ID: (metaEnv.NEXT_PUBLIC_FIREBASE_APP_ID || metaEnv.VITE_FIREBASE_APP_ID || '') as string,
  FIREBASE_MEASUREMENT_ID: (metaEnv.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID || metaEnv.VITE_FIREBASE_MEASUREMENT_ID || '') as string,
  GOOGLE_MAPS_API_KEY: (metaEnv.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || metaEnv.VITE_GOOGLE_MAPS_API_KEY || '') as string,
  RAZORPAY_KEY_ID: (metaEnv.NEXT_PUBLIC_RAZORPAY_KEY_ID || metaEnv.VITE_RAZORPAY_KEY_ID || '') as string,
};
